apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database
  namespace: ssdev
spec:
  encryptedData:
    password: AgAo0EOMz/SaqNf71GiCndqw6FIh13ZG6ePopaVBa4gFyebKeVjrgHs0Z9HDeOx1duPfAITA6kH3mHWCvSR64MwtlSinJydtWQJJdPU0cMbt/VX0eVcF59tJohA/Mp6gMzD7GR1re0w3WD5g17BxaS3hE8oqvnYjO/tBzdPp0U3TtQ4vKlXsXXOYIwrBWy4tf4TTVW0j5xbhnWVdcMQ3tKCJ7BGu31dCIxh0nbY6FcKR9ICQ30dYHTM+w2nJDFBojCFnd5TiHC/GYeD+heVyE7zuvUYG7tyPzbXDjWuGs9WBHRjkaCOiPowkna0mXxWJVYia67hGf3pOggQ2fzxCS8pUXF4zfccrVXQHAgIuAOe9SOsR4oIcCYhD3GnK6/68ybZAA1fM9T05GT1yPcdl6BNfl/38RHd3WIivfvUgdRwjf4skIVAKeb4XcBSLHE06vDC8A+SSbLxoX+6EznAkWiQjfeSDPzdn0b+DOBD2sClksPs5PLsQyBv0F9r5HBtXzYZ2Zh0Mnh5CMzzelxd+lLxXW4eC8iXozTanpsmnuFKC+Gjzp1OtGTeIWedMdnlFWoDMkq1iQXcyppJFlxkYT1ixKSgA9Hw25MN002BvLOFFvNIUrLV14gxUJonzrOjaolt+Z/5eG/qYv6wGCOxGR4RZKdGYLDzi79/zt2uCBehWFNis3P3f6ipYsOlHN5F279/BwOhvbovRsZKwHZKSsScOrRbWWg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database
      namespace: ssdev

